urls:
  company:
    root: companies
    employees:
      root: employees

---
spring:
  profiles: polish
urls:
  company:
    root: firmy
    emplyees:
      root: pracownicy

---
spring:
  profiles: spanish
urls:
  company:
  root: empresas
  emplyees:
    root: empleadores
